project/leagues/models.py
from project import db

class League(db.Model):

  __tablename__ = 'leagues'

  id = db.Column(db.Integer, primary_key=True)
  year = db.Column(db.Integer)
  name = db.Column(db.Text)
  season_id = db.Column(db.Integer, db.ForeignKey('seasons.id'))
  teams = db.relationship('Team', order_by="Team.name", backref='league', lazy='dynamic')
  scorecards = db.relationship('Scorecard', backref='league', lazy='dynamic')

  def __init__(self, year, name, season_id):
    self.year = year 
    self.name = name
    self.season_id = season_id

  def __repr__(self):
    return "#{}: year: {} - name: {} - season_id: {}".format(self.id, self.year, self.name, self.season_id)

project/matches/models.py
from project import db

class Match(db.Model):

  __tablename__ = 'matches'

  id = db.Column(db.Integer, primary_key=True)
  scorecard_id = db.Column(db.Integer, db.ForeignKey('scorecards.id'))
  match_type = db.Column(db.Text)
  line = db.Column(db.Integer)
  h_1_player_id = db.Column(db.Integer)
  h_1_player_name = db.Column(db.Text)
  h_2_player_id = db.Column(db.Integer)
  h_2_player_name = db.Column(db.Text)
  v_1_player_id = db.Column(db.Integer)
  v_1_player_name = db.Column(db.Text)
  v_2_player_id = db.Column(db.Integer)
  v_2_player_name = db.Column(db.Text)
  winning_score = db.Column(db.Text)
  winner = db.Column(db.Text)

  #I use this in displaying the matches for a team to highlight if
  #the current team is home or visitor (which is based on scoredcard table data)
  are_home = None

  def __repr__(self):
    return "#{}: scorecard_id: {} - match_type: {} - line: {}".format(self.id, self.scorecard_id, self.match_type, self.line)

project/players/models.py
from project import db

class Player(db.Model):

  __tablename__ = 'players'

  id = db.Column(db.Integer, primary_key=True)
  player_id = db.Column(db.Integer)
  name = db.Column(db.Text)
  city = db.Column(db.Text)
  gender = db.Column(db.Text)
  rating = db.Column(db.Text)
  np_sw = db.Column(db.Text)
  expiration = db.Column(db.Text)
  won = db.Column(db.Integer)
  lost = db.Column(db.Integer)
  matches = db.Column(db.Integer)
  defaults = db.Column(db.Integer)
  win_percent = db.Column(db.Integer)
  singles = db.Column(db.Integer)
  doubles = db.Column(db.Integer)
  team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))

  #should team ID be a separate thing - can I init with it?
  def __init__(self, name, rating):
    self.name = name
    self.rating = rating

  def __repr__(self):
    return "#{}: name: {} - rating: {}".format(self.id, self.name, self.rating)

project/rosters/models.py
from project import db
from sqlalchemy import PrimaryKeyConstraint

class Roster(db.Model):

  __tablename__ = 'rosters'

  __table_args__ = (
        PrimaryKeyConstraint('team_id', 'player_id'),
        {},)
  player_id = db.Column(db.Integer)
  name = db.Column(db.Text)
  city = db.Column(db.Text)
  gender = db.Column(db.Text)
  rating = db.Column(db.Text)
  np_sw = db.Column(db.Text)
  expiration = db.Column(db.Text)
  won = db.Column(db.Integer)
  lost = db.Column(db.Integer)
  matches = db.Column(db.Integer)
  defaults = db.Column(db.Integer)
  win_percent = db.Column(db.Integer)
  singles = db.Column(db.Integer)
  doubles = db.Column(db.Integer)
  team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))

  #should team ID be a separate thing - can I init with it?
  def __init__(self, name, rating):
    self.name = name
    self.rating = rating

  def __repr__(self):
    return "player_id: {} - name: {} - rating: {}".format(self.player_id, self.name, self.rating)

project/scorecards/models.py
from project import db

class Scorecard(db.Model):

  __tablename__ = 'scorecards'

  id = db.Column(db.Integer, primary_key=True)
  home_team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
  visitor_team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
  date = db.Column(db.DateTime)
  league_id = db.Column(db.Integer, db.ForeignKey('leagues.id'))
  matches = db.relationship('Match', backref='scorecard', lazy='dynamic')

  def __init__(self, date, home_team_id, visitor_team_id):
    self.date = date 
    self.home_team_id = home_team_id
    self.visitor_team_id = visitor_team_id

  def __repr__(self):
    return "#{}: date: {} - home_team_id: {} - visitor_team_id: {}".format(self.id, self.date, self.home_team_id, self.visitor_team_id)

project/seasons/models.py
from project import db

class Season(db.Model):

  __tablename__ = 'seasons'

  id = db.Column(db.Integer, primary_key=True)
  year = db.Column(db.Integer)
  name = db.Column(db.Text)
  leagues = db.relationship('League', order_by="League.name", backref='season', lazy='dynamic')
  teams = db.relationship('Team', order_by="Team.name", backref='season', lazy='dynamic')

  def __init__(self, year, name):
    self.year = year 
    self.name = name

  def __repr__(self):
    return "#{}: year: {} - name: {}".format(self.id, self.year, self.name)

project/teams/models.py
from project import db

class Team(db.Model):

  __tablename__ = 'teams'

  id = db.Column(db.Integer, primary_key=True)
  league_id = db.Column(db.Integer, db.ForeignKey('leagues.id'))
  season_id = db.Column(db.Integer, db.ForeignKey('seasons.id'))
  org_id = db.Column(db.Integer)
  facility_id = db.Column(db.Integer)
  name = db.Column(db.Text)
  area = db.Column(db.Text)
  num_match_scheduled = db.Column(db.Integer)
  num_match_played = db.Column(db.Integer)
  matches_won = db.Column(db.Integer)
  matches_lost = db.Column(db.Integer)
  rosters = db.relationship('Roster', backref='team', lazy='dynamic')
  h_scorecards = db.relationship('Scorecard', foreign_keys='Scorecard.home_team_id', backref='team_h', lazy='dynamic')
  v_scorecards = db.relationship('Scorecard', foreign_keys='Scorecard.visitor_team_id', backref='team_v', lazy='dynamic')

  #should team ID be a separate thing - can I init with it?
  def __init__(self, season_id, name, area):
    self.season_id = season_id
    self.name = name
    self.area = area

  def __repr__(self):
    return "#{}: name: {} - area: {}".format(self.id, self.name, self.area)

project/__init__.py
from flask import Flask, redirect, url_for, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
import os

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL') or 'postgres://localhost/chart-my-team-db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_ECHO'] = False
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or "it's a secret"

modus = Modus(app)
db = SQLAlchemy(app)

from project.teams.views import teams_blueprint
from project.rosters.views import rosters_blueprint
from project.seasons.views import seasons_blueprint
from project.leagues.views import leagues_blueprint
from project.scorecards.views import scorecards_blueprint
from project.matches.views import matches_blueprint

from project.scorecards.models import Scorecard
from project.matches.models import Match

app.register_blueprint(teams_blueprint, url_prefix='/teams')
app.register_blueprint(seasons_blueprint, url_prefix='/seasons')
app.register_blueprint(leagues_blueprint, url_prefix='/leagues')
app.register_blueprint(scorecards_blueprint, url_prefix='/scorecards') #url_prefix='/teams/<int:id>/scorecards')
app.register_blueprint(matches_blueprint, url_prefix='/matches')
app.register_blueprint(rosters_blueprint, url_prefix='/rosters')

@app.route('/')
def root(): 
  return render_template('/index.html')

@app.route('/about')
def about():
    return render_template('/about.html')

@app.after_request
def add_header(r):
    """
    Add headers to both force latest IE rendering engine or Chrome Frame,
    and also to cache the rendered page for 10 minutes.
    """
    r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    r.headers["Pragma"] = "no-cache"
    r.headers["Expires"] = "0"
    r.headers['Cache-Control'] = 'public, max-age=0'
    return r

project/leagues/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify
from project.leagues.models import League

leagues_blueprint = Blueprint(
  'leagues',
  __name__,
  template_folder='templates'
)

@leagues_blueprint.route('/json')
def json():
  # leagues_list_2 = []
  # leagues_sub = League.query.filter(League.year>=2015).order_by(League.id.desc()).all()
  # for l in leagues_sub:
  #   leagues_list_2.append(l.id)
  # print(len(leagues_list_2))
  # print(leagues_list_2)

  leagues_list = []
  for l in League.query.order_by(League.year.desc(), League.name.asc()).all():
    leagues_list.append({
      'id': l.id,
      'year': l.year,
      'name': l.name,
      'season_id': l.season_id
    })
  return jsonify(leagues_list)

@leagues_blueprint.route('/<int:id>/json')
def teams_json(id):
  curr_league = League.query.get(id)
  teams_list = []
  # teams_id_list = []
  for t in curr_league.teams.all():
    # teams_id_list.append(t.id)
    teams_list.append({
      'id': t.id,
      'league_id': t.league_id,
      'season_id': t.season_id,
      'name': t.name,
      'area': t.area,
      'num_match_scheduled': t.num_match_scheduled,
      'num_match_played': t.num_match_played,
      'matches_won': t.matches_won,
      'matches_lost': t.matches_lost
    })
  # print(teams_id_list)
  return jsonify(teams_list)

project/matches/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify
from project.matches.models import Match
from project import db

matches_blueprint = Blueprint(
  'matches',
  __name__,
  template_folder='templates'
)

@matches_blueprint.route('/')
def index():
  matches = Match.query.all()
  return render_template('matches/index.html', matches=matches)

project/players/views.py
from flask import redirect, render_template, request, url_for, Blueprint 
from project.players.models import Player
from project import db

players_blueprint = Blueprint(
  'players',
  __name__,
  template_folder='templates'
)

@players_blueprint.route('/')
def index():
  return "hello"
  # return render_template('messages/new.html', form=form)

project/rosters/views.py
from flask import redirect, render_template, request, url_for, Blueprint 
from project.rosters.models import Roster
from project import db

rosters_blueprint = Blueprint(
  'rosters',
  __name__,
  template_folder='templates'
)

@rosters_blueprint.route('/')
def index():
  return "hello"
  # return render_template('messages/new.html', form=form)

project/scorecards/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify
from project.scorecards.models import Scorecard
from project import db

scorecards_blueprint = Blueprint(
  'scorecards',
  __name__,
  template_folder='templates'
)

@scorecards_blueprint.route('/')
def index(id):
  scorecards = Scorecard.query.filter((Scorecard.home_team_id==id)|(Scorecard.visitor_team_id==id)).order_by(Scorecard.date.asc()).all()

  # for scorecard in scorecards:
  #   from IPython import embed; embed()
  return render_template('scorecards/index.html', scorecards=scorecards)


@scorecards_blueprint.route('/<int:id>/matches')
def matches(id):
  scorecard = Scorecard.query.get(id)
  matches = scorecard.matches.all()
  return render_template('scorecards/matches.html', matches=matches, scorecard=scorecard)

project/seasons/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify 
from project.seasons.models import Season

seasons_blueprint = Blueprint(
  'seasons',
  __name__,
  template_folder='templates'
)

@seasons_blueprint.route('/json')
def json():
  seasons_list = []
  #THIS IS WHERE SET THE FILTER FOR SEASONS!
  #for s in Season.query.filter(Season.year>=2015).order_by(Season.year.desc(), Season.name.asc()).all():
  for s in Season.query.filter(Season.id.in_([192, 201, 204])).order_by(Season.year.desc(), Season.name.asc()).all():
    seasons_list.append({
      'id': s.id,
      'year': s.year,
      'name': s.name
    })
  return jsonify(seasons_list)

@seasons_blueprint.route('/<int:id>/json')
def leagues_json(id):
  curr_season = Season.query.get(id)
  leagues_list = []
  for l in curr_season.leagues.all():
    leagues_list.append({
      'id': l.id,
      'year': l.year,
      'name': l.name
    })
  return jsonify(leagues_list)

@seasons_blueprint.route('/<int:id>/teamsjson')
def teams_json(id):
  curr_season = Season.query.get(id)
  teams_list = []
  for t in curr_season.teams.all():
    teams_list.append({
      'id': t.id,
      'league_id': t.league_id,
      'season_id': t.season_id,
      'name': t.name,
      'area': t.area,
      'num_match_scheduled': t.num_match_scheduled,
      'num_match_played': t.num_match_played,
      'matches_won': t.matches_won,
      'matches_lost': t.matches_lost
    })
  return jsonify(teams_list)

project/teams/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify
from project.teams.models import Team

teams_blueprint = Blueprint(
  'teams',
  __name__,
  template_folder='templates'
)

@teams_blueprint.route('/')
def index():
  # areas = db.session.query(Team.area.distinct()).all() #NEED TO FIX THIS TO LIMIT IT!!!
  return render_template('teams/index.html')

@teams_blueprint.route('/<int:id>')
def show(id):
  curr_team = Team.query.get(id)
  #seasons = Season.query.filter(Season.year>=2015).order_by(Season.year.desc(), Season.name.asc()).all()
  if len(curr_team.rosters.all()) > 0:
    has_rosters = True
  else:
    has_rosters = False
  return render_template('teams/show.html', curr_team=curr_team, has_rosters=has_rosters)

@teams_blueprint.route('/<int:id>/scorecards')
def scorecards(id):
  curr_team = Team.query.get(id)
  #n+1 query FIX LATER!!!
  scorecards_h = curr_team.h_scorecards.all()
  scorecards_v = curr_team.v_scorecards.all()
  scorecards = scorecards_h + scorecards_v
  #sort by date
  scorecards.sort(key=lambda x: x.date, reverse=False)  
  return render_template('teams/scorecards.html', scorecards=scorecards, curr_team = curr_team)

@teams_blueprint.route('/<int:id>/matches')
def matches(id):
  curr_team = Team.query.get(id)
  #n+1 query FIX LATER!!!
  scorecards_h = curr_team.h_scorecards.all()
  scorecards_v = curr_team.v_scorecards.all()
  scorecards = scorecards_h + scorecards_v
  scorecards.sort(key=lambda x: x.date, reverse=False)  

  matches = []
  for scorecard in scorecards:
    matches += scorecard.matches.all()

  for match in matches:
    if match.scorecard.team_h.id == id:
      match.are_home = True
    else:
      match.are_home = False

  return render_template('teams/matches.html', matches=matches, curr_team=curr_team)

@teams_blueprint.route('/<int:id>/matches_json')
def matches_json(id):
  curr_team = Team.query.get(id)
  #n+1 query FIX LATER!!!
  scorecards_h = curr_team.h_scorecards.all()
  scorecards_v = curr_team.v_scorecards.all()
  scorecards = scorecards_h + scorecards_v
  scorecards.sort(key=lambda x: x.date, reverse=False) 

  matches = []
  for scorecard in scorecards:
    matches += scorecard.matches.all()

  for match in matches:
    if match.scorecard.team_h.id == id:
      match.are_home = True
    else:
      match.are_home = False

  json_matches_list = []

  for m in matches:
    obj = {
      'id': m.id,
      'scorecard_id': m.scorecard.id,
      'type': m.match_type,
      'line': m.line,
      'winning_score': m.winning_score
    }
    obj['date'] = m.scorecard.date.strftime('%m-%d-%y')
    if m.are_home:
      obj['location'] = 'Home'
      obj['opponent'] = m.scorecard.team_v.name
      obj['opponent_id'] = m.scorecard.team_v.id
      obj['team_player_1'] = m.h_1_player_name
      obj['team_player_1_id'] = m.h_1_player_id
      obj['opp_player_1'] = m.v_1_player_name
      obj['opp_player_1_id'] = m.v_1_player_id
      if m.match_type == 'doubles':
        obj['team_player_2'] = m.h_2_player_name
        obj['team_player_2_id'] = m.h_2_player_id
        obj['opp_player_2'] = m.v_2_player_name
        obj['opp_player_2_id'] = m.v_2_player_id
    else:
      obj['location'] = 'Away'
      obj['opponent'] = m.scorecard.team_h.name
      obj['opponent_id'] = m.scorecard.team_h.id
      obj['team_player_1'] = m.v_1_player_name
      obj['team_player_1_id'] = m.v_1_player_id
      obj['opp_player_1'] = m.h_1_player_name
      obj['opp_player_1_id'] = m.h_1_player_id
      if m.match_type == 'doubles':
        obj['team_player_2'] = m.v_2_player_name
        obj['team_player_2_id'] = m.v_2_player_id
        obj['opp_player_2'] = m.h_2_player_name
        obj['opp_player_2_id'] = m.h_2_player_id
    if m.match_type != 'doubles':
        obj['team_player_2'] = ''
        obj['team_player_2_id'] = ''
        obj['opp_player_2'] = ''
        obj['opp_player_2_id'] = ''
    if m.are_home:
      if m.winner == 'Home':
        obj['winner'] = 'Team'
      else:
        obj['winner'] = 'Opponent'
    else:
      if m.winner == 'Home':
        obj['winner'] = 'Opponent'
      else:
        obj['winner'] = 'Team'

    json_matches_list.append(obj)

  return jsonify(json_matches_list)


@teams_blueprint.route('/<int:id>/json')
def team_json(id):
  curr_team = Team.query.get(id)
  rosters_list = []
  for r in curr_team.rosters.all():
    rosters_list.append({
      'team_id': r.team_id,
      'player_id': r.player_id,
      'name': r.name,
      'city': r.city,
      'gender': r.gender,
      'rating': r.rating,
      'np_sw': r.np_sw,
      'expiration': r.expiration,
      'won': r.won,
      'lost': r.lost,
      'matches': r.matches,
      'defaults': r.defaults,
      'win_percent': r.win_percent,
      'singles': r.singles,
      'doubles': r.doubles,
      'team_name': curr_team.name,
      'area': curr_team.area
    })
  return jsonify(rosters_list)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chart My Team</title>
    <link
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block style %}
    {% endblock %}
    <script
      src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">
    <script
      src="//code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>

</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-custom navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Nav Bar: toggle for mobile, Brand -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span> 
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div>
          <a class="navbar-brand" href="{{url_for('root')}}">
            <svg class="svgRacket" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50px" height="50px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
              <g><g><g><path d="M921,890.1L740.9,687l0.6-0.4l-2.2-1.4l-42.4-47.8c-4.1-4.7-9-8.3-14.1-11.4c-23.9-37-48.3-95.4-49.7-180c7.1-25.4,10.5-52.7,9.8-81.5c-0.3-13.2-3.6-30.2-7.8-47.6c-10.3,5.6-21.3,9.6-32.7,12.7c13.7,82.6-8,161.2-66.4,208.3c-97.4,78.9-259.1,40.3-361.2-86C72.8,325.7,68.9,159.5,166.3,80.8c76-61.4,191-51.3,286.5,16c2.9-3.5,5.6-7.1,8.9-10.4c4.2-4.3,8.8-8,13.5-11.7c-39-27.7-70.4-42.4-70.4-42.4S342.5,8.2,293.9,10.1c-56.7,0-108.2,18-148.8,51.9c-111,93-107.9,280.1,6.9,417.2c64,76.3,152.1,123.7,239.3,130.5l0,1.4c1.2,0.1,112,6.2,210.8,98.7c1.6,2.4,3.2,4.9,5.2,7.1l224,252.9c21.9,24.8,59.8,27,84.7,5C940.8,952.9,943.1,915,921,890.1z M612.4,632.3c-11.9,10.5-18.5,24.6-19.8,39.2c-43.8-34.9-87.6-55.3-123.2-67c34.4-8,65.6-23.1,92.1-45.4c21.6-18,39-39.9,52.3-64.6c6.3,51.7,21,92.1,37.3,122.9C637.3,617.7,623.5,622.5,612.4,632.3z"/><path d="M437.3,189.2c28.3,3.3,58.4,17.8,83,42.4c24.7,24.7,39.2,54.9,42.4,83.1c25.8-2.4,51-13.5,70.7-33.3c19.8-19.7,30.9-44.9,33.2-70.6c-28.2-3.3-58.3-17.8-83-42.4c-24.7-24.7-39.1-54.8-42.4-83.1c-25.8,2.4-50.9,13.5-70.7,33.3C450.8,138.3,439.7,163.4,437.3,189.2z"/><path d="M667.1,196.5c-0.8-28.3-12-56.3-33.6-78c-21.6-21.5-49.7-32.8-78-33.7c3.2,24.8,16.3,51.4,38.3,73.4C615.8,180.2,642.4,193.3,667.1,196.5z"/><path d="M436.9,203.5c0.9,28.3,12,56.4,33.6,78c21.6,21.6,49.7,32.9,77.9,33.6c-3.1-24.7-16.3-51.3-38.3-73.3C488.2,219.8,461.6,206.7,436.9,203.5z"/></g></g></g>
            </svg>
            <span id="brandSpan">Chart My Team</span>
          </a>
        </div>
      </div> <!-- /.navbar-header -->

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li {% block teamActive %}{% endblock%}>
            <a href="{{url_for('teams.index')}}">Teams</a>
          </li>
          <li {% block aboutActive %}{% endblock%}>
            <a href="{{url_for('about')}}">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="space"></div>

  <div class="container">

    {% block content %}

    {% endblock %}
  </div>

  {% block table %}
  {% endblock %}

  <footer>
    <div class="footerCopyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            Created by <a href="http://www.juliahazer.com" target="_blank">Julia Hazer</a> | 
            Data from <a href="http://www.norcal.usta.com/" target="_blank">USTA NorCal</a>
          </div>
        </div>
      </div>
    </div>
  </footer>


  <!-- jQuery -->
  <script
    src="//code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
  <!-- Bootstrap js -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- Custom JavaScript -->
  {% block scripts %}
  {% endblock %}

</body>
</html>

project/templates/teamnav.html
<!--form-->
<div class='container-fluid' id="teamNavMenu">
  <div class="form-group row" id="selectTeamViewDiv">
    <div class="col-lg-3 col-lg-offset-2
      col-md-2 col-md-offset-2
      col-sm-3 col-sm-offset-1
      col-xs-12
      col-form-label">
      <label id="selectTeamViewLabel" 
        for="selectTeamView"> 
        Pages for this team:
      </label>
    </div>
    <div class="col-lg-3 col-lg-offset-0
      col-md-6 col-md-offset-0
      col-sm-7 col-sm-offset-0
      col-xs-10 col-xs-offset-1">
      <select onchange="location = this.value;" class="form-control" id="teamViewSelect">
        <option value="{{url_for('teams.show', id = curr_team.id)}}">Team Graphs</option>
        <option value="{{url_for('teams.matches', id =curr_team.id)}}">Team Matches</option>
        <option value="{{url_for('teams.scorecards', id=curr_team.id)}}">Team Scorecards</option>
      </select>
    </div>
  </div>
</div>